# Generated by Django 5.2.7 on 2025-10-08 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_material', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('job', models.IntegerField()),
            ],
        ),
    ]
